WillBooster/wbfy

src/generators/packageJson.ts

feat: fill UNLICENSED in license field if needed

---

src/generators/editorconfig.ts
src/generators/gitattributes.ts
src/index.ts
src/utils/extensions.ts

feat: support .gitattributes

---

.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/inspectionProfiles/Project_Default.xml
.idea/willboosterify.iml
src/generators/editorconfig.ts
src/generators/gitattributes.ts
src/generators/gitignore.ts
src/generators/lintstagedrc.ts
src/generators/packageJson.ts
src/generators/prettierignore.ts
src/generators/renovatercJson.ts
src/index.ts
src/types/packageConfig.ts
src/utils/extensions.ts
src/utils/fsUtil.ts
src/utils/spawnUtil.ts

feat: support Flutter projects

---

src/generators/lintstagedrc.ts

fix: support lint-staged v10

---

src/generators/lintstagedrc.ts
src/generators/packageJson.ts

feat: yarn sort-package-json in lint-staged

---

src/generators/eslintignore.ts
src/generators/prettierignore.ts

fix: don't format *.min.js

---

src/generators/gitignore.ts

fix: ignore .idea/misc.xml

---

src/generators/packageJson.ts
src/generators/tsconfig.ts
src/index.ts
src/types/packageConfig.ts

feat: don't refer to tsconfig.json in node_modules for yarn v2

---

src/generators/editorconfig.ts

fix: don't add unnecessary {} in .editorconfig

---

src/generators/tsconfig.ts
src/utils/packageConfig.ts

feat: add ../../@types in tsconfig and improve tsnode support

---

src/generators/eslintignore.ts
src/generators/prettierignore.ts

feat: ignore *.d.ts in linters and formatters

---

src/generators/eslintignore.ts
src/generators/prettierignore.ts

fix: ignore android/ and ios/ in formatter and linter

---

src/generators/packageJson.ts

feat: install typescript if repo has ts files

---

src/generators/idea.ts

fix(idea): don't watch external changes

---

src/generators/eslintrc.ts
src/generators/gitignore.ts
src/generators/huskyrc.ts
src/generators/idea.ts
src/generators/lintstagedrc.ts
src/generators/packageJson.ts
src/generators/tsconfig.ts
src/index.ts
src/utils/packageConfig.ts

feat: don't apply formatter / linter to files in packages from root

---

package.json
src/generators/eslintrc.ts
src/generators/huskyrc.ts
src/generators/idea.ts
src/generators/lernaJson.ts
src/generators/lintstagedrc.ts
src/generators/packageJson.ts
src/generators/renovaterc.ts
src/generators/tsconfig.ts
src/generators/yarnrc.ts
src/utils/fsUtil.ts
src/utils/ignoreFileUtil.ts
yarn.lock

refactor: employ fs/promises instead of fs-extra

---

package.json
yarn.lock

Revert "chore(deps): update dependency semantic-release to v19"

---

src/github/label.ts

feat(label): setup labels on GitHub repository

---

src/github/label.ts

feat(label): generate more labels

---

src/generators/readme.ts

Close #303 
バッジを最初の改行文字の直後に順に追加していくよう実装しています。

feat(readme): add test badge (GitHub Actions badge) if `.github/workflows/test.yml`, `deploy.yml` or `deploy-XXX.yml` exist

---

src/generators/vscodeSettings.ts

Close #<IssueNumber>
- You may leave this box unchecked due to long workflows.
- PR title follows [Angular's commit message format](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format).
- PR title doesn't have `WIP:`.
- All tests are passed.
- Test command (e.g., `yarn test`) is passed.
- Lint command (e.g., `yarn lint`) is passed.
- You may leave this box unchecked if you didn't modify the UI.

feat: disable vscode auto format

---

src/utils/spawnUtil.ts

Close #<IssueNumber>
- PR title follows [Angular's commit message format](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format).
- PR title doesn't have `WIP:`.
- The test command (e.g., `yarn test`) passed.
- The lint command (e.g., `yarn lint`) passed.
- You may leave this box unchecked due to long workflows.
- You may leave this box unchecked if you didn't modify the UI.

fix: support the latest asdf
